


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."event_trigger_fn"() RETURNS "event_trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  -- Add logic here
END;
$$;


ALTER FUNCTION "public"."event_trigger_fn"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_auth_user_ban_or_delete"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  -- If the user is being marked as deleted, clean up their profile.
  if new.deleted_at is not null and (old.deleted_at is distinct from new.deleted_at) then
    delete from public.profiles where id = new.id;
    return new;
  end if;

  -- If the user becomes banned/suspended, clean up their profile.
  if old.banned_until is null and new.banned_until is not null then
    delete from public.profiles where id = new.id;
    return new;
  end if;

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_auth_user_ban_or_delete"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_auth_user_cleanup"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  v_uid uuid := new.id;
begin
  -- 1) Remove from community members arrays
  update public."Communities"
  set members = array_remove(members, v_uid)
  where members is not null
    and members @> array[v_uid];

  -- 2) Delete posts authored by the user
  delete from public."Posts"
  where user_id = v_uid;

  -- 3) Delete communities owned by the user
  delete from public."Communities"
  where user_id = v_uid;

  -- 4) Delete profile row (FK cascade handles deletes too, but keep it consistent)
  delete from public.profiles where id = v_uid;

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_auth_user_cleanup"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.profiles (id, username, birthday)
  values (
    new.id,
    nullif(new.raw_user_meta_data->>'username', '')::text,
    case
      when nullif(new.raw_user_meta_data->>'birthday', '') is null then null
      else (new.raw_user_meta_data->>'birthday')::date
    end
  )
  on conflict (id) do update set
    username = excluded.username,
    birthday = excluded.birthday;

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user_fn"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  v_username text;
begin
  v_username := nullif(new.raw_user_meta_data->>'username', '')::text;

  insert into public.profiles (id, username, display_name, birthday)
  values (
    new.id,
    v_username,
    v_username,
    case
      when nullif(new.raw_user_meta_data->>'birthday', '') is null then null
      else (new.raw_user_meta_data->>'birthday')::date
    end
  )
  on conflict (id) do update set
    username = excluded.username,
    display_name = excluded.display_name,
    birthday = excluded.birthday;

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user_fn"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Communities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "description" "text",
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "banner_url" "text",
    "members" "uuid"[],
    "global" boolean DEFAULT false,
    "latitude" double precision,
    "longitude" double precision,
    "radius_meters" integer
);


ALTER TABLE "public"."Communities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."PostReports" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "post_id" "uuid",
    "reporter_id" "uuid"
);


ALTER TABLE "public"."PostReports" OWNER TO "postgres";


ALTER TABLE "public"."PostReports" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PostReports_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "community" "uuid" DEFAULT "gen_random_uuid"(),
    "title" "text",
    "body" "text",
    "communityName" "text",
    "post_type" "text",
    "img_link" "text"
);


ALTER TABLE "public"."Posts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text" NOT NULL,
    "display_name" "text",
    "bio" "text",
    "avatar_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "joined_communities" "uuid"[],
    "admin" boolean DEFAULT false,
    "FirstTimeOpen" boolean DEFAULT true,
    "Language" "text" DEFAULT 'en'::"text",
    "birthday" "date",
    "requestedDelete" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Communities"
    ADD CONSTRAINT "Communities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PostReports"
    ADD CONSTRAINT "PostReports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Posts"
    ADD CONSTRAINT "Posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow users to update everything except admin status" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK ((("auth"."uid"() = "id") AND (NOT ("admin" IS DISTINCT FROM ( SELECT "p"."admin"
   FROM "public"."profiles" "p"
  WHERE ("p"."id" = "auth"."uid"()))))));



ALTER TABLE "public"."Communities" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable delete for users based on user_id" ON "public"."Communities" FOR DELETE USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") AND ("global" IS NOT TRUE)));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."Posts" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."PostReports" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."Communities" FOR INSERT WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") AND ("global" IS NOT TRUE)));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."Posts" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Enable read access for all users" ON "public"."Communities" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Posts" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Enable update for authenticated users only" ON "public"."Communities" FOR UPDATE TO "authenticated" USING ((true AND ("global" IS NOT TRUE)));



ALTER TABLE "public"."PostReports" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Posts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."event_trigger_fn"() TO "anon";
GRANT ALL ON FUNCTION "public"."event_trigger_fn"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."event_trigger_fn"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_auth_user_ban_or_delete"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_auth_user_ban_or_delete"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_auth_user_ban_or_delete"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_auth_user_cleanup"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_auth_user_cleanup"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_auth_user_cleanup"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user_fn"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user_fn"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user_fn"() TO "service_role";



GRANT ALL ON TABLE "public"."Communities" TO "anon";
GRANT ALL ON TABLE "public"."Communities" TO "authenticated";
GRANT ALL ON TABLE "public"."Communities" TO "service_role";



GRANT ALL ON TABLE "public"."PostReports" TO "anon";
GRANT ALL ON TABLE "public"."PostReports" TO "authenticated";
GRANT ALL ON TABLE "public"."PostReports" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PostReports_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PostReports_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PostReports_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Posts" TO "anon";
GRANT ALL ON TABLE "public"."Posts" TO "authenticated";
GRANT ALL ON TABLE "public"."Posts" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
