import {
  createContext,
  type PropsWithChildren,
  useCallback,
  useContext,
  useEffect,
  useState,
} from 'react';

import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

export type LanguageCode = 'en' | 'es';

const strings = {
  en: {
    appearance: 'Appearance',
    language: 'Language',

    // Tab bar
    tabHome: 'Home',
    tabCommunities: 'Communities',
    tabCreate: 'Create',
    tabCalendar: 'Calendar',
    tabSettings: 'Settings',

    // Screen header titles
    headerPost: 'Post',
    headerSupporter: 'Supporter',
    headerCreateCommunity: 'Create Community',
    headerEditProfile: 'Edit Profile',
    headerSubCommunity: 'Sub-community',
    headerMap: 'Map',
    headerActivity: 'Activity',
    headerPrivacyPolicy: 'Privacy Policy',
    headerTermsOfService: 'Terms of Service',
    headerEarlyAccess: 'Early Access',
    headerCommunity: 'Community',
    headerCreateSubCommunity: 'Create Sub-community',
    headerEditPost: 'Edit Post',
    headerSettings: 'Settings',

    // Common actions
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    logOut: 'Log out',
    back: 'Back',
    post: 'Post',
    follow: 'Follow',
    unfollow: 'Unfollow',
    block: 'Block',
    report: 'Report',
    search: 'Search',
    loading: 'Loading',
    retry: 'Retry',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    done: 'Done',
    share: 'Share',
    signIn: 'Sign in',
    signUp: 'Sign up',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password',

    // Login screen
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to continue to Bloom.',
    loginButton: 'Sign in',
    loginMissingFields: 'Enter your email and password to continue.',
    genericError: 'Something went wrong. Please try again.',
    forgotPasswordLink: 'Forgot your password?',
    loginNewToBloom: 'New to Bloom?',
    loginCreateAccount: 'Create an account',

    // Register screen
    registerTitle: 'Join Bloom',
    registerSubtitle: 'Create an account to connect with your local communities.',
    registerUsernamePlaceholder: 'Username',
    registerPasswordHelp: 'At least 8 characters, with an uppercase letter, a lowercase letter, and a number.',
    registerDateOfBirth: 'Date of birth',
    registerAgreeToPrefix: 'I agree to the',
    registerAgreeToAnd: 'and',
    registerCreateAccountButton: 'Create account',
    registerAlreadyHaveAccount: 'Already have an account? Log in',
    registerFillAllFields: 'Fill in every field to continue.',
    registerAcceptTermsRequired: 'You must accept the Terms of Service to continue.',
    registerUsernameNotAllowed: 'That username isn’t allowed. Please choose another.',
    registerUsernameTaken: 'That username is already taken.',
    registerCheckEmailTitle: 'Check your email',
    registerCheckEmailMessage: 'We sent you a confirmation link to finish creating your account.',
    registerFailedGeneric: 'Registration could not be completed.',

    // Reset password screen
    resetLinkInvalid: 'This reset link is invalid or has expired.',
    resetEnterEmail: 'Enter your email to continue.',
    resetPasswordsMismatch: 'Passwords do not match.',
    resetPasswordUpdateFailed: 'Could not update your password. Please try again.',
    resetPasswordUpdatedTitle: 'Password updated',
    resetPasswordUpdatedDescription: 'Your password has been changed successfully. Please sign in again.',
    resetGoToLogin: 'Go to login',
    resetSetNewPasswordTitle: 'Set a new password',
    resetSetNewPasswordDescription: 'Choose a new password for your account.',
    resetNewPasswordPlaceholder: 'New password',
    resetConfirmPasswordPlaceholder: 'Confirm new password',
    resetUpdatePasswordButton: 'Update password',
    resetYourPasswordTitle: 'Reset your password',
    resetYourPasswordDescription: 'Enter your email and we’ll send you a link to reset your password.',
    resetLinkSentMessage: 'If an account exists for that email, a reset link is on its way.',
    resetSendLinkButton: 'Send reset link',
    resetBackToLogin: 'Back to login',

    // Confirm screen
    confirmEmailConfirmedTitle: 'Email confirmed',
    confirmEmailConfirmedDescription: 'Your email has been confirmed. You can now sign in to your account.',
    confirmContinueToLogin: 'Continue to login',
    confirmLinkExpiredTitle: 'Link expired',
    confirmLinkExpiredDescription: 'This confirmation link is invalid or has expired. Please try registering again.',

    // Validators
    validatorPasswordRequirements: 'Password must be at least 8 characters, with an uppercase letter, a lowercase letter, and a number.',
    validatorUsernameLength: 'Username must be between 3 and 30 characters.',
    validatorUsernameChars: 'Username can only contain letters, numbers, and underscores.',
    validatorBirthdayRequired: 'Date of birth is required.',
    validatorAgeMinimum: 'You must be at least 13 years old to sign up.',
    validatorBirthdayInvalid: 'Please enter a valid date of birth.',

    // Settings screen
    settingsEnterCurrentPassword: 'Enter your current password to continue.',
    settingsNewPasswordsMismatch: 'New passwords do not match.',
    settingsCurrentPasswordIncorrect: 'Current password is incorrect.',
    settingsPasswordUpdatedTitle: 'Password updated',
    settingsPasswordUpdatedMessage: 'Your password has been changed successfully.',
    settingsPasswordChangeFailed: 'Could not update your password. Please try again.',
    settingsChangePassword: 'Change password',
    settingsCurrentPasswordPlaceholder: 'Current password',
    settingsUpdateButton: 'Update',
    settingsTypeDeleteToConfirm: 'Type DELETE to confirm.',
    settingsAccountDeleteFailed: 'Could not delete your account. Please try again.',
    settingsDeleteAccount: 'Delete account',
    settingsDeleteAccountWarning: 'This will permanently delete your account and all of your data. This action cannot be undone.',
    settingsDeleteMyAccount: 'Delete my account',
    settingsThemeUnavailableTitle: 'Theme unavailable',
    settingsThemeApplyFailed: 'Could not apply that theme. Please try again.',
    settingsConnectTitle: 'Connect',
    settingsConnectUpdateFailed: 'Could not update your connect settings. Please try again.',
    settingsLogOutConfirm: 'Are you sure you want to log out?',
    settingsEditProfile: 'Edit profile',
    settingsEditProfileSubtitle: 'Update your photo, bio, and profile details.',
    settingsAppearanceDescription: 'Choose how Bloom looks on your device.',
    settingsSupporterHint: 'Become a supporter to unlock more themes.',
    settingsLanguageDescription: 'Choose the language used throughout the app.',
    settingsEarlyAccessDescription: 'Try upcoming features before everyone else.',
    settingsEarlyAccessTitle: 'Early access',
    settingsOpenEarlyAccess: 'Open early access',
    settingsConnectDescription: 'Let nearby members discover and connect with you.',
    settingsConnectOn: 'On',
    settingsConnectOff: 'Off',
    settingsViewConnections: 'View connections',
    settingsSupporterDescription: 'Manage your supporter status and benefits.',
    settingsManageSupporterStatus: 'Manage supporter status',
    settingsAccountSettingsDescription: 'Manage your password and account access.',
    settingsAccountSettingsTitle: 'Account',
    settingsLegalTitle: 'Legal',

    // Activity screen
    activityLoadFailed: 'Could not load activity. Please try again.',
    activityEmptySearch: 'No results match your search.',
    activityEmptyMy: 'You haven’t posted any activities or events yet.',
    activityEmptyNearby: 'No nearby activities or events right now.',
    activityEmptyLocationRequired: 'Enable location to see what’s nearby.',
    activityEmptyDefault: 'No activities or events yet. Check back soon.',
    activitySearchPlaceholder: 'Search activities and events',
    activityFilterAll: 'All',
    activityFilterActivity: 'Activities',
    activityFilterEvent: 'Events',
    activityScopeAll: 'Everywhere',
    activityScopeMy: 'Mine',
    activityScopeNearby: 'Nearby',
    activityLoading: 'Loading activity…',
    activityEmptyTitle: 'Nothing here yet',

    // Calendar screen
    weekdaySun: 'Sun',
    weekdayMon: 'Mon',
    weekdayTue: 'Tue',
    weekdayWed: 'Wed',
    weekdayThu: 'Thu',
    weekdayFri: 'Fri',
    weekdaySat: 'Sat',
    monthJanuary: 'January',
    monthFebruary: 'February',
    monthMarch: 'March',
    monthApril: 'April',
    monthMay: 'May',
    monthJune: 'June',
    monthJuly: 'July',
    monthAugust: 'August',
    monthSeptember: 'September',
    monthOctober: 'October',
    monthNovember: 'November',
    monthDecember: 'December',
    calendarOpenMap: 'Open map',
    calendarLoading: 'Loading calendar…',
    calendarNoCommunitiesHelp: 'Join a community to see its events here.',
    calendarNoCommunitiesTitle: 'No communities yet',
    calendarPreviousMonth: 'Previous month',
    calendarNextMonth: 'Next month',
    calendarSelectDay: 'Select a day',
    calendarTapDayHint: 'Tap a day to see its events.',
    calendarNoEventsForDay: 'No events on this day.',
    calendarLoadFailed: 'Could not load your calendar. Please try again.',

    // Home screen
    homeAuthRequired: 'Authentication required.',
    homeConnect: 'Connect',
    homeLoadingFeed: 'Loading your feed…',
    homeNoPostsTitle: 'No posts yet',
    homeEmptyFeedHelp: 'Join a community to start seeing posts in your feed.',

    // Create post screen
    createSubmitButton: 'Post',
    createMissingInfoTitle: 'Missing information',
    createMissingInfoMessage: 'Please fill in a title and description before posting.',
    createCommunityRequiredTitle: 'Community required',
    createCommunityRequiredMessage: 'Choose a community to post in.',
    createLocationRequiredTitle: 'Location required',
    createLocationRequiredMessage: 'Add a location for this event or activity.',
    createPostFailed: 'Could not create your post. Please try again.',
    createPostCreatedTitle: 'Post created',
    createPostCreatedMessage: 'Your post has been shared successfully.',
    createViewFeed: 'View feed',
    createUnableToCreateTitle: 'Unable to create post',
    createTryAgain: 'Something went wrong. Please try again.',
    createLocationSelected: 'Location selected',
    createTapTheMap: 'Tap the map to select a location',
    createEventLocationMarker: 'Event location',
    createPostTo: 'Post to',
    createJoinToPost: 'Join a community to post.',
    createCircleLabel: 'Sub-community',
    createMainFeed: 'Main feed',
    createTitlePlaceholder: 'Title',
    createDescriptionPlaceholder: 'Description',
    createEventDate: 'Event date',

    // Communities screen
    communitiesJoinedTitle: 'Joined',
    communitiesJoinedMessage: 'You’ve joined this community.',
    communitiesAlreadyMemberTitle: 'Already a member',
    communitiesAlreadyMemberMessage: 'You’re already a member of this community.',
    communitiesOutOfRangeTitle: 'Out of range',
    communitiesOutOfRangeMessage: 'You must be within this community’s area to join.',
    communitiesRequestSentTitle: 'Request sent',
    communitiesRequestSentMessage: 'Your request to join has been sent for approval.',
    communitiesRequestPendingTitle: 'Request pending',
    communitiesRequestPendingMessage: 'Your request to join is still pending approval.',
    communitiesLeftTitle: 'Left community',
    communitiesLeftMessage: 'You’ve left this community.',
    communitiesNotMemberTitle: 'Not a member',
    communitiesNotMemberMessage: 'You’re not a member of this community.',
    communitiesCantLeaveTitle: 'Can’t leave',
    communitiesCantLeaveMessage: 'As the owner, you can’t leave this community.',
    communitiesLoadFailed: 'Could not load communities. Please try again.',
    communitiesSomethingWentWrong: 'Something went wrong',
    communitiesMemberCount: '{count} members',
    communitiesLeaveCommunityLabel: 'Leave community',
    communitiesJoinCommunityLabel: 'Join community',
    communitiesLeave: 'Leave',
    communitiesJoin: 'Join',
    communitiesLoading: 'Loading communities…',
    communitiesNearbySection: 'Nearby',
    communitiesNoneNearbyHelp: 'No communities near you yet.',
    communitiesEnableLocationHelp: 'Enable location to see communities near you.',
    communitiesNothingNearbyTitle: 'Nothing nearby',
    communitiesMineSection: 'My communities',
    communitiesNoneJoinedHelp: 'Communities you join will show up here.',
    communitiesNoneJoinedTitle: 'No communities joined',

    // Create community screen
    createCommunityNameLength: 'Community name must be between 3 and 50 characters.',
    createCommunityDescriptionLength: 'Description must be between 10 and 500 characters.',
    createCommunityLocationRequired: 'Location is required.',
    createCommunityFailed: 'Could not create the community. Please try again.',
    createCommunityNameLabel: 'Community name',
    createCommunityNamePlaceholder: 'e.g. Downtown Runners',
    createCommunityDescriptionLabel: 'Description',
    createCommunityDescriptionPlaceholder: 'What is this community about?',
    createCommunityPictureHint: 'Add a picture and banner to help people recognize your community.',
    createCommunityRadiusLabel: 'Radius',
    createCommunityDecreaseRadius: 'Decrease radius',
    createCommunityIncreaseRadius: 'Increase radius',
    createCommunitySupporterRadiusHint: 'As a supporter, you can set a larger radius.',
    createCommunityNonSupporterRadiusHint: 'Become a supporter to unlock a larger radius.',
    createCommunityPrivateLabel: 'Private community',
    createCommunityPrivateHint: 'New members must be approved before joining.',
    createCommunitySubmitButton: 'Create community',

    // Community detail screen
    communitiesOwnerLabel: 'Owner',
    communitiesOutsideAreaLabel: 'Outside area',
    communitiesRequestToJoin: 'Request to join',
    communitiesLeaveCommunity: 'Leave community',
    communitiesJoinCommunity: 'Join community',
    communitiesNameLength: 'Community name must be between 3 and 50 characters.',
    communitiesUpdateFailed: 'Could not update the community. Please try again.',
    communitiesPhotoAccessTitle: 'Photo access needed',
    communitiesPhotoAccessPictureMessage: 'Allow photo access to update the community picture.',
    communitiesPhotoAccessBannerMessage: 'Allow photo access to update the community banner.',
    communitiesUploadFailedTitle: 'Upload failed',
    communitiesPictureUpdateFailed: 'Could not update the picture. Please try again.',
    communitiesBannerUpdateFailed: 'Could not update the banner. Please try again.',
    communitiesScopeBusiness: 'Business',
    communitiesScopeGlobal: 'Global',
    communitiesScopePrivate: 'Private',
    communitiesScopeLocal: 'Local',
    communitiesBannerRemoveFailed: 'Could not remove the banner. Please try again.',
    communitiesPrivacyUpdateFailed: 'Could not update privacy settings. Please try again.',
    communitiesRequestUnavailableTitle: 'Request unavailable',
    communitiesRequestUnavailableMessage: 'Join requests aren’t available for this community right now.',
    communitiesDeleteTitle: 'Delete community',
    communitiesDeleteConfirm: 'Are you sure you want to delete this community? This cannot be undone.',
    communitiesDeleteFailed: 'Could not delete the community. Please try again.',
    communitiesNotFoundTitle: 'Community not found',
    communitiesNotFoundHelp: 'This community may have been removed or doesn’t exist.',
    communitiesPleaseWait: 'Please wait…',
    communitiesMembersHeading: 'Members',
    communitiesDefaultUserName: 'Member',
    communitiesSubcommunitiesHeading: 'Sub-communities',
    communitiesOwnerBadge: 'Owner',
    communitiesJoinedBadge: 'Joined',
    communitiesNoSubcommunities: 'No sub-communities yet.',
    communitiesCreateSubcommunity: 'Create sub-community',
    communitiesOwnerToolsHeading: 'Owner tools',
    communitiesNameLabel: 'Name',
    communitiesEditNameDescription: 'Edit name & description',
    communitiesChangePicture: 'Change picture',
    communitiesChangeBanner: 'Change banner',
    communitiesRemoveBanner: 'Remove banner',
    communitiesPendingRequestsHeading: 'Pending requests',
    communitiesApprove: 'Approve',
    communitiesDeny: 'Deny',
    communitiesDeleteCommunity: 'Delete community',
    communitiesPostsHeading: 'Posts',
    communitiesNoPostsYet: 'No posts yet.',

    // Sub-community screens
    subTitleLength: 'Title must be between 3 and 50 characters.',
    subDuplicateError: 'A sub-community with that name already exists.',
    subCreateFailed: 'Could not create the sub-community. Please try again.',
    subTitleLabel: 'Title',
    subTitlePlaceholder: 'e.g. Book Club',
    subDescriptionPlaceholder: 'What is this sub-community about?',
    subCreateButton: 'Create sub-community',
    subAlreadyMemberTitle: 'Already a member',
    subAlreadyMemberMessage: 'You’re already a member of this sub-community.',
    subJoinedTitle: 'Joined',
    subJoinedMessage: 'You’ve joined this sub-community.',
    subUpdateFailed: 'Could not update the sub-community. Please try again.',
    subDeleteTitle: 'Delete sub-community',
    subDeleteConfirm: 'Are you sure you want to delete this sub-community? This cannot be undone.',
    subDeleteFailed: 'Could not delete the sub-community. Please try again.',
    subNotFoundTitle: 'Sub-community not found',
    subNotFoundHelp: 'This sub-community may have been removed or doesn’t exist.',
    subInParent: 'In {name}',
    subJoinButton: 'Join',
    subManagerToolsHeading: 'Manager tools',
    subEditTitleDescription: 'Edit title & description',
    subDeleteButton: 'Delete sub-community',
    subNoPostsYet: 'No posts yet.',

    // Connect screen
    connectConnectedOn: 'Connected on',
    connectLoadFailed: 'Could not load your connections. Please try again.',
    connectLoading: 'Loading connections…',
    connectActive: 'Active',
    connectActiveLooking: 'Active — looking for connections',
    connectGoBack: 'Go back',
    connectRefresh: 'Refresh',
    connectEnabledHelp: 'You’re visible to nearby Bloom users with Connect enabled.',
    connectDisabledHelp: 'Turn on Connect to be discovered by nearby Bloom users.',
    connectEnableLabel: 'Enable Connect',
    connectPrivacyNote: 'Your exact location is never shared — only that you were nearby.',
    connectPeopleHeading: 'People you’ve connected with',
    connectEmptyTitle: 'No connections yet',
    connectEmptyHelp: 'When you cross paths with other Connect users, they’ll show up here.',

    // Early access screen
    earlyAccessSupporterTitle: 'You’re a supporter',
    earlyAccessHasAccess: 'You have early access to upcoming features.',
    earlyAccessRequiredTitle: 'Supporter required',
    earlyAccessRequiredBody: 'Become a supporter to unlock early access to upcoming features.',
    earlyAccessViewSupporter: 'View supporter options',

    // Map screen
    mapLoadFailed: 'Could not load the map. Please try again.',
    mapLoadingEvents: 'Loading events…',
    mapEmptyHelp: 'No events to show on the map right now.',
    mapDismiss: 'Dismiss',
    mapInCommunity: 'In {name}',
    mapViewEvent: 'View event',

    // Supporter screen
    supporterLoadFailed: 'Could not load supporter status. Please try again.',
    supporterConnectFailed: 'Could not connect to the supporter checkout. Please try again.',
    supporterLoadingStatus: 'Loading supporter status…',
    supporterSignInPrompt: 'Sign in to view your supporter status.',
    supporterActiveTitle: 'You’re a supporter',
    supporterLinkedTitle: 'Account linked',
    supporterNotConnectedTitle: 'Not connected',
    supporterActiveBody: 'Thank you for supporting Bloom. You have access to supporter perks.',
    supporterLinkedBody: 'Your Patreon account is linked, but supporter status isn’t active yet.',
    supporterNotConnectedBody: 'Connect your Patreon account to become a supporter and unlock perks.',
    supporterVerifiedOn: 'Verified on {date}',
    supporterReconnect: 'Reconnect',
    supporterConnect: 'Connect Patreon',

    // Post detail screen
    postYou: 'You',
    postNotFoundTitle: 'Post not found',
    postNotFoundHelp: 'This post may have been removed or doesn’t exist.',
    postNoRepliesYet: 'No replies yet. Be the first to reply.',
    postRepliesHeading: 'Replies',
    postWriteReplyPlaceholder: 'Write a reply…',
    postSendReply: 'Send reply',

    // Edit post screen
    postEditMissingFields: 'Please fill in a title and description before saving.',
    postEditUpdatedTitle: 'Post updated',
    postEditOk: 'OK',
    postEditUpdateFailed: 'Could not update your post. Please try again.',
    postEditForbiddenTitle: 'Can’t edit this post',
    postEditForbiddenHelp: 'You don’t have permission to edit this post.',
    postEditSaveChanges: 'Save changes',

    // Public profile screen
    profileUnblockConfirmTitle: 'Unblock user',
    profileBlockConfirmTitle: 'Block user',
    profileUnblockConfirmMessage: 'They’ll be able to see your posts and interact with you again.',
    profileBlockConfirmMessage: 'You won’t see each other’s posts or be able to interact.',
    profileUnblock: 'Unblock',
    profileBlock: 'Block',
    profileMoreOptions: 'More options',
    profileTitle: 'Profile',
    profileNotFoundTitle: 'Profile not found',
    profileBlockedHelp: 'You’ve blocked this user.',
    profileNoPostsHelp: 'This user hasn’t posted anything yet.',
    profileUserBlockedTitle: 'User blocked',
    profileNoPostsTitle: 'No posts yet',

    // Edit profile screen
    profileEditPhotoAccessMessage: 'Allow photo access to update your profile picture.',
    profileEditUnsupportedFileTitle: 'Unsupported file',
    profileEditUnsupportedFileSupporterMessage: 'Choose a JPEG, PNG, WEBP, or GIF image.',
    profileEditUnsupportedFileMessage: 'Choose a JPEG, PNG, or WEBP image. GIFs are a supporter perk.',
    profileEditFileTooLargeTitle: 'File too large',
    profileEditFileTooLargeMessage: 'Choose an image under {size}MB.',
    profileEditDisplayNameLength: 'Display name must be between 1 and 50 characters.',
    profileEditBioLength: 'Bio must be {limit} characters or fewer.',
    profileEditUpdatedTitle: 'Profile updated',
    profileEditUpdatedMessage: 'Your changes have been saved.',
    profileEditUpdateFailed: 'Your profile could not be updated.',
    profileEditChangePhoto: 'Change photo',
    profileEditDisplayName: 'Display name',
    profileEditUsername: 'Username',
    profileEditBio: 'Bio',
    profileEditBioPlaceholder: 'Tell your communities about yourself',

    // Post card / options menu
    postAlreadyReportedTitle: 'Already reported',
    postReportedTitle: 'Reported',
    postAlreadyReportedMessage: 'You’ve already reported this post.',
    postReportedMessage: 'Thanks for letting us know. Our team will review this post.',
    postDeleteTitle: 'Delete post',
    postDeleteConfirm: 'Are you sure you want to delete this post? This cannot be undone.',
    postCouldNotDeleteTitle: 'Could not delete',
    postManageTitle: 'Manage post',
    postOptionsTitle: 'Post options',
    postReportPost: 'Report post',
    postLocationLabel: 'Location:',
    postPostedOn: 'Posted on {date}',
    postUnlike: 'Unlike',
    postLike: 'Like',
    postLikeCount: '{count} likes',
    postReplyCount: '{count} replies',
  },
  es: {
    appearance: 'Apariencia',
    language: 'Idioma',

    // Tab bar
    tabHome: 'Inicio',
    tabCommunities: 'Comunidades',
    tabCreate: 'Crear',
    tabCalendar: 'Calendario',
    tabSettings: 'Ajustes',

    // Screen header titles
    headerPost: 'Publicación',
    headerSupporter: 'Colaborador',
    headerCreateCommunity: 'Crear comunidad',
    headerEditProfile: 'Editar perfil',
    headerSubCommunity: 'Subcomunidad',
    headerMap: 'Mapa',
    headerActivity: 'Actividad',
    headerPrivacyPolicy: 'Política de privacidad',
    headerTermsOfService: 'Términos de servicio',
    headerEarlyAccess: 'Acceso anticipado',
    headerCommunity: 'Comunidad',
    headerCreateSubCommunity: 'Crear subcomunidad',
    headerEditPost: 'Editar publicación',
    headerSettings: 'Ajustes',

    // Common actions
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    logOut: 'Cerrar sesión',
    back: 'Atrás',
    post: 'Publicar',
    follow: 'Seguir',
    unfollow: 'Dejar de seguir',
    block: 'Bloquear',
    report: 'Reportar',
    search: 'Buscar',
    loading: 'Cargando',
    retry: 'Reintentar',
    confirm: 'Confirmar',
    yes: 'Sí',
    no: 'No',
    done: 'Listo',
    share: 'Compartir',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    forgotPassword: 'Olvidé mi contraseña',

    // Login screen
    loginTitle: 'Bienvenido de nuevo',
    loginSubtitle: 'Inicia sesión para continuar en Bloom.',
    loginButton: 'Iniciar sesión',
    loginMissingFields: 'Ingresa tu correo electrónico y contraseña para continuar.',
    genericError: 'Algo salió mal. Inténtalo de nuevo.',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    loginNewToBloom: '¿Nuevo en Bloom?',
    loginCreateAccount: 'Crear una cuenta',

    // Register screen
    registerTitle: 'Únete a Bloom',
    registerSubtitle: 'Crea una cuenta para conectarte con tus comunidades locales.',
    registerUsernamePlaceholder: 'Nombre de usuario',
    registerPasswordHelp: 'Al menos 8 caracteres, con una mayúscula, una minúscula y un número.',
    registerDateOfBirth: 'Fecha de nacimiento',
    registerAgreeToPrefix: 'Acepto los',
    registerAgreeToAnd: 'y la',
    registerCreateAccountButton: 'Crear cuenta',
    registerAlreadyHaveAccount: '¿Ya tienes una cuenta? Inicia sesión',
    registerFillAllFields: 'Completa todos los campos para continuar.',
    registerAcceptTermsRequired: 'Debes aceptar los Términos de servicio para continuar.',
    registerUsernameNotAllowed: 'Ese nombre de usuario no está permitido. Elige otro.',
    registerUsernameTaken: 'Ese nombre de usuario ya está en uso.',
    registerCheckEmailTitle: 'Revisa tu correo',
    registerCheckEmailMessage: 'Te enviamos un enlace de confirmación para terminar de crear tu cuenta.',
    registerFailedGeneric: 'No se pudo completar el registro.',

    // Reset password screen
    resetLinkInvalid: 'Este enlace de restablecimiento no es válido o ha expirado.',
    resetEnterEmail: 'Ingresa tu correo electrónico para continuar.',
    resetPasswordsMismatch: 'Las contraseñas no coinciden.',
    resetPasswordUpdateFailed: 'No se pudo actualizar tu contraseña. Inténtalo de nuevo.',
    resetPasswordUpdatedTitle: 'Contraseña actualizada',
    resetPasswordUpdatedDescription: 'Tu contraseña se cambió correctamente. Vuelve a iniciar sesión.',
    resetGoToLogin: 'Ir a iniciar sesión',
    resetSetNewPasswordTitle: 'Establece una nueva contraseña',
    resetSetNewPasswordDescription: 'Elige una nueva contraseña para tu cuenta.',
    resetNewPasswordPlaceholder: 'Nueva contraseña',
    resetConfirmPasswordPlaceholder: 'Confirmar nueva contraseña',
    resetUpdatePasswordButton: 'Actualizar contraseña',
    resetYourPasswordTitle: 'Restablece tu contraseña',
    resetYourPasswordDescription: 'Ingresa tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.',
    resetLinkSentMessage: 'Si existe una cuenta con ese correo, te enviaremos un enlace en camino.',
    resetSendLinkButton: 'Enviar enlace',
    resetBackToLogin: 'Volver a iniciar sesión',

    // Confirm screen
    confirmEmailConfirmedTitle: 'Correo confirmado',
    confirmEmailConfirmedDescription: 'Tu correo ha sido confirmado. Ya puedes iniciar sesión en tu cuenta.',
    confirmContinueToLogin: 'Continuar a iniciar sesión',
    confirmLinkExpiredTitle: 'Enlace expirado',
    confirmLinkExpiredDescription: 'Este enlace de confirmación no es válido o ha expirado. Intenta registrarte de nuevo.',

    // Validators
    validatorPasswordRequirements: 'La contraseña debe tener al menos 8 caracteres, con una mayúscula, una minúscula y un número.',
    validatorUsernameLength: 'El nombre de usuario debe tener entre 3 y 30 caracteres.',
    validatorUsernameChars: 'El nombre de usuario solo puede contener letras, números y guiones bajos.',
    validatorBirthdayRequired: 'La fecha de nacimiento es obligatoria.',
    validatorAgeMinimum: 'Debes tener al menos 13 años para registrarte.',
    validatorBirthdayInvalid: 'Ingresa una fecha de nacimiento válida.',

    // Settings screen
    settingsEnterCurrentPassword: 'Ingresa tu contraseña actual para continuar.',
    settingsNewPasswordsMismatch: 'Las nuevas contraseñas no coinciden.',
    settingsCurrentPasswordIncorrect: 'La contraseña actual es incorrecta.',
    settingsPasswordUpdatedTitle: 'Contraseña actualizada',
    settingsPasswordUpdatedMessage: 'Tu contraseña se cambió correctamente.',
    settingsPasswordChangeFailed: 'No se pudo actualizar tu contraseña. Inténtalo de nuevo.',
    settingsChangePassword: 'Cambiar contraseña',
    settingsCurrentPasswordPlaceholder: 'Contraseña actual',
    settingsUpdateButton: 'Actualizar',
    settingsTypeDeleteToConfirm: 'Escribe DELETE para confirmar.',
    settingsAccountDeleteFailed: 'No se pudo eliminar tu cuenta. Inténtalo de nuevo.',
    settingsDeleteAccount: 'Eliminar cuenta',
    settingsDeleteAccountWarning: 'Esto eliminará permanentemente tu cuenta y todos tus datos. Esta acción no se puede deshacer.',
    settingsDeleteMyAccount: 'Eliminar mi cuenta',
    settingsThemeUnavailableTitle: 'Tema no disponible',
    settingsThemeApplyFailed: 'No se pudo aplicar ese tema. Inténtalo de nuevo.',
    settingsConnectTitle: 'Conectar',
    settingsConnectUpdateFailed: 'No se pudo actualizar tu configuración de conexión. Inténtalo de nuevo.',
    settingsLogOutConfirm: '¿Seguro que quieres cerrar sesión?',
    settingsEditProfile: 'Editar perfil',
    settingsEditProfileSubtitle: 'Actualiza tu foto, biografía y datos de perfil.',
    settingsAppearanceDescription: 'Elige cómo se ve Bloom en tu dispositivo.',
    settingsSupporterHint: 'Conviértete en colaborador para desbloquear más temas.',
    settingsLanguageDescription: 'Elige el idioma que se usa en toda la aplicación.',
    settingsEarlyAccessDescription: 'Prueba las próximas funciones antes que nadie.',
    settingsEarlyAccessTitle: 'Acceso anticipado',
    settingsOpenEarlyAccess: 'Abrir acceso anticipado',
    settingsConnectDescription: 'Permite que otros miembros cercanos te descubran y conecten contigo.',
    settingsConnectOn: 'Activado',
    settingsConnectOff: 'Desactivado',
    settingsViewConnections: 'Ver conexiones',
    settingsSupporterDescription: 'Administra tu estado de colaborador y beneficios.',
    settingsManageSupporterStatus: 'Administrar estado de colaborador',
    settingsAccountSettingsDescription: 'Administra tu contraseña y acceso a la cuenta.',
    settingsAccountSettingsTitle: 'Cuenta',
    settingsLegalTitle: 'Legal',

    // Activity screen
    activityLoadFailed: 'No se pudo cargar la actividad. Inténtalo de nuevo.',
    activityEmptySearch: 'Ningún resultado coincide con tu búsqueda.',
    activityEmptyMy: 'Aún no has publicado ninguna actividad o evento.',
    activityEmptyNearby: 'No hay actividades o eventos cercanos por ahora.',
    activityEmptyLocationRequired: 'Activa la ubicación para ver lo que hay cerca.',
    activityEmptyDefault: 'Aún no hay actividades ni eventos. Vuelve pronto.',
    activitySearchPlaceholder: 'Buscar actividades y eventos',
    activityFilterAll: 'Todo',
    activityFilterActivity: 'Actividades',
    activityFilterEvent: 'Eventos',
    activityScopeAll: 'En todas partes',
    activityScopeMy: 'Mías',
    activityScopeNearby: 'Cerca',
    activityLoading: 'Cargando actividad…',
    activityEmptyTitle: 'Aún no hay nada',

    // Calendar screen
    weekdaySun: 'Dom',
    weekdayMon: 'Lun',
    weekdayTue: 'Mar',
    weekdayWed: 'Mié',
    weekdayThu: 'Jue',
    weekdayFri: 'Vie',
    weekdaySat: 'Sáb',
    monthJanuary: 'Enero',
    monthFebruary: 'Febrero',
    monthMarch: 'Marzo',
    monthApril: 'Abril',
    monthMay: 'Mayo',
    monthJune: 'Junio',
    monthJuly: 'Julio',
    monthAugust: 'Agosto',
    monthSeptember: 'Septiembre',
    monthOctober: 'Octubre',
    monthNovember: 'Noviembre',
    monthDecember: 'Diciembre',
    calendarOpenMap: 'Abrir mapa',
    calendarLoading: 'Cargando calendario…',
    calendarNoCommunitiesHelp: 'Únete a una comunidad para ver sus eventos aquí.',
    calendarNoCommunitiesTitle: 'Aún no hay comunidades',
    calendarPreviousMonth: 'Mes anterior',
    calendarNextMonth: 'Mes siguiente',
    calendarSelectDay: 'Selecciona un día',
    calendarTapDayHint: 'Toca un día para ver sus eventos.',
    calendarNoEventsForDay: 'No hay eventos en este día.',
    calendarLoadFailed: 'No se pudo cargar tu calendario. Inténtalo de nuevo.',

    // Home screen
    homeAuthRequired: 'Se requiere autenticación.',
    homeConnect: 'Conectar',
    homeLoadingFeed: 'Cargando tu feed…',
    homeNoPostsTitle: 'Aún no hay publicaciones',
    homeEmptyFeedHelp: 'Únete a una comunidad para empezar a ver publicaciones en tu feed.',

    // Create post screen
    createSubmitButton: 'Publicar',
    createMissingInfoTitle: 'Falta información',
    createMissingInfoMessage: 'Completa un título y una descripción antes de publicar.',
    createCommunityRequiredTitle: 'Comunidad requerida',
    createCommunityRequiredMessage: 'Elige una comunidad en la cual publicar.',
    createLocationRequiredTitle: 'Ubicación requerida',
    createLocationRequiredMessage: 'Agrega una ubicación para este evento o actividad.',
    createPostFailed: 'No se pudo crear tu publicación. Inténtalo de nuevo.',
    createPostCreatedTitle: 'Publicación creada',
    createPostCreatedMessage: 'Tu publicación se compartió correctamente.',
    createViewFeed: 'Ver feed',
    createUnableToCreateTitle: 'No se pudo crear la publicación',
    createTryAgain: 'Algo salió mal. Inténtalo de nuevo.',
    createLocationSelected: 'Ubicación seleccionada',
    createTapTheMap: 'Toca el mapa para seleccionar una ubicación',
    createEventLocationMarker: 'Ubicación del evento',
    createPostTo: 'Publicar en',
    createJoinToPost: 'Únete a una comunidad para publicar.',
    createCircleLabel: 'Subcomunidad',
    createMainFeed: 'Feed principal',
    createTitlePlaceholder: 'Título',
    createDescriptionPlaceholder: 'Descripción',
    createEventDate: 'Fecha del evento',

    // Communities screen
    communitiesJoinedTitle: 'Te uniste',
    communitiesJoinedMessage: 'Te has unido a esta comunidad.',
    communitiesAlreadyMemberTitle: 'Ya eres miembro',
    communitiesAlreadyMemberMessage: 'Ya eres miembro de esta comunidad.',
    communitiesOutOfRangeTitle: 'Fuera de rango',
    communitiesOutOfRangeMessage: 'Debes estar dentro del área de esta comunidad para unirte.',
    communitiesRequestSentTitle: 'Solicitud enviada',
    communitiesRequestSentMessage: 'Tu solicitud para unirte fue enviada para aprobación.',
    communitiesRequestPendingTitle: 'Solicitud pendiente',
    communitiesRequestPendingMessage: 'Tu solicitud para unirte sigue pendiente de aprobación.',
    communitiesLeftTitle: 'Comunidad abandonada',
    communitiesLeftMessage: 'Has dejado esta comunidad.',
    communitiesNotMemberTitle: 'No eres miembro',
    communitiesNotMemberMessage: 'No eres miembro de esta comunidad.',
    communitiesCantLeaveTitle: 'No puedes salir',
    communitiesCantLeaveMessage: 'Como propietario, no puedes salir de esta comunidad.',
    communitiesLoadFailed: 'No se pudieron cargar las comunidades. Inténtalo de nuevo.',
    communitiesSomethingWentWrong: 'Algo salió mal',
    communitiesMemberCount: '{count} miembros',
    communitiesLeaveCommunityLabel: 'Salir de la comunidad',
    communitiesJoinCommunityLabel: 'Unirse a la comunidad',
    communitiesLeave: 'Salir',
    communitiesJoin: 'Unirse',
    communitiesLoading: 'Cargando comunidades…',
    communitiesNearbySection: 'Cerca de ti',
    communitiesNoneNearbyHelp: 'Aún no hay comunidades cerca de ti.',
    communitiesEnableLocationHelp: 'Activa la ubicación para ver comunidades cerca de ti.',
    communitiesNothingNearbyTitle: 'Nada cerca',
    communitiesMineSection: 'Mis comunidades',
    communitiesNoneJoinedHelp: 'Las comunidades a las que te unas aparecerán aquí.',
    communitiesNoneJoinedTitle: 'No te has unido a ninguna comunidad',

    // Create community screen
    createCommunityNameLength: 'El nombre de la comunidad debe tener entre 3 y 50 caracteres.',
    createCommunityDescriptionLength: 'La descripción debe tener entre 10 y 500 caracteres.',
    createCommunityLocationRequired: 'La ubicación es obligatoria.',
    createCommunityFailed: 'No se pudo crear la comunidad. Inténtalo de nuevo.',
    createCommunityNameLabel: 'Nombre de la comunidad',
    createCommunityNamePlaceholder: 'p. ej. Corredores del centro',
    createCommunityDescriptionLabel: 'Descripción',
    createCommunityDescriptionPlaceholder: '¿De qué trata esta comunidad?',
    createCommunityPictureHint: 'Agrega una foto y un banner para que la gente reconozca tu comunidad.',
    createCommunityRadiusLabel: 'Radio',
    createCommunityDecreaseRadius: 'Disminuir radio',
    createCommunityIncreaseRadius: 'Aumentar radio',
    createCommunitySupporterRadiusHint: 'Como colaborador, puedes establecer un radio mayor.',
    createCommunityNonSupporterRadiusHint: 'Conviértete en colaborador para desbloquear un radio mayor.',
    createCommunityPrivateLabel: 'Comunidad privada',
    createCommunityPrivateHint: 'Los nuevos miembros deben ser aprobados antes de unirse.',
    createCommunitySubmitButton: 'Crear comunidad',

    // Community detail screen
    communitiesOwnerLabel: 'Propietario',
    communitiesOutsideAreaLabel: 'Fuera del área',
    communitiesRequestToJoin: 'Solicitar unirse',
    communitiesLeaveCommunity: 'Salir de la comunidad',
    communitiesJoinCommunity: 'Unirse a la comunidad',
    communitiesNameLength: 'El nombre de la comunidad debe tener entre 3 y 50 caracteres.',
    communitiesUpdateFailed: 'No se pudo actualizar la comunidad. Inténtalo de nuevo.',
    communitiesPhotoAccessTitle: 'Acceso a fotos necesario',
    communitiesPhotoAccessPictureMessage: 'Permite el acceso a fotos para actualizar la foto de la comunidad.',
    communitiesPhotoAccessBannerMessage: 'Permite el acceso a fotos para actualizar el banner de la comunidad.',
    communitiesUploadFailedTitle: 'Error al subir',
    communitiesPictureUpdateFailed: 'No se pudo actualizar la foto. Inténtalo de nuevo.',
    communitiesBannerUpdateFailed: 'No se pudo actualizar el banner. Inténtalo de nuevo.',
    communitiesScopeBusiness: 'Negocio',
    communitiesScopeGlobal: 'Global',
    communitiesScopePrivate: 'Privada',
    communitiesScopeLocal: 'Local',
    communitiesBannerRemoveFailed: 'No se pudo quitar el banner. Inténtalo de nuevo.',
    communitiesPrivacyUpdateFailed: 'No se pudo actualizar la configuración de privacidad. Inténtalo de nuevo.',
    communitiesRequestUnavailableTitle: 'Solicitud no disponible',
    communitiesRequestUnavailableMessage: 'Las solicitudes para unirse no están disponibles en esta comunidad por ahora.',
    communitiesDeleteTitle: 'Eliminar comunidad',
    communitiesDeleteConfirm: '¿Seguro que quieres eliminar esta comunidad? Esta acción no se puede deshacer.',
    communitiesDeleteFailed: 'No se pudo eliminar la comunidad. Inténtalo de nuevo.',
    communitiesNotFoundTitle: 'Comunidad no encontrada',
    communitiesNotFoundHelp: 'Es posible que esta comunidad haya sido eliminada o no exista.',
    communitiesPleaseWait: 'Espera un momento…',
    communitiesMembersHeading: 'Miembros',
    communitiesDefaultUserName: 'Miembro',
    communitiesSubcommunitiesHeading: 'Subcomunidades',
    communitiesOwnerBadge: 'Propietario',
    communitiesJoinedBadge: 'Unido',
    communitiesNoSubcommunities: 'Aún no hay subcomunidades.',
    communitiesCreateSubcommunity: 'Crear subcomunidad',
    communitiesOwnerToolsHeading: 'Herramientas del propietario',
    communitiesNameLabel: 'Nombre',
    communitiesEditNameDescription: 'Editar nombre y descripción',
    communitiesChangePicture: 'Cambiar foto',
    communitiesChangeBanner: 'Cambiar banner',
    communitiesRemoveBanner: 'Quitar banner',
    communitiesPendingRequestsHeading: 'Solicitudes pendientes',
    communitiesApprove: 'Aprobar',
    communitiesDeny: 'Rechazar',
    communitiesDeleteCommunity: 'Eliminar comunidad',
    communitiesPostsHeading: 'Publicaciones',
    communitiesNoPostsYet: 'Aún no hay publicaciones.',

    // Sub-community screens
    subTitleLength: 'El título debe tener entre 3 y 50 caracteres.',
    subDuplicateError: 'Ya existe una subcomunidad con ese nombre.',
    subCreateFailed: 'No se pudo crear la subcomunidad. Inténtalo de nuevo.',
    subTitleLabel: 'Título',
    subTitlePlaceholder: 'p. ej. Club de lectura',
    subDescriptionPlaceholder: '¿De qué trata esta subcomunidad?',
    subCreateButton: 'Crear subcomunidad',
    subAlreadyMemberTitle: 'Ya eres miembro',
    subAlreadyMemberMessage: 'Ya eres miembro de esta subcomunidad.',
    subJoinedTitle: 'Te uniste',
    subJoinedMessage: 'Te has unido a esta subcomunidad.',
    subUpdateFailed: 'No se pudo actualizar la subcomunidad. Inténtalo de nuevo.',
    subDeleteTitle: 'Eliminar subcomunidad',
    subDeleteConfirm: '¿Seguro que quieres eliminar esta subcomunidad? Esta acción no se puede deshacer.',
    subDeleteFailed: 'No se pudo eliminar la subcomunidad. Inténtalo de nuevo.',
    subNotFoundTitle: 'Subcomunidad no encontrada',
    subNotFoundHelp: 'Es posible que esta subcomunidad haya sido eliminada o no exista.',
    subInParent: 'En {name}',
    subJoinButton: 'Unirse',
    subManagerToolsHeading: 'Herramientas del administrador',
    subEditTitleDescription: 'Editar título y descripción',
    subDeleteButton: 'Eliminar subcomunidad',
    subNoPostsYet: 'Aún no hay publicaciones.',

    // Connect screen
    connectConnectedOn: 'Conectado el',
    connectLoadFailed: 'No se pudieron cargar tus conexiones. Inténtalo de nuevo.',
    connectLoading: 'Cargando conexiones…',
    connectActive: 'Activo',
    connectActiveLooking: 'Activo — buscando conexiones',
    connectGoBack: 'Volver',
    connectRefresh: 'Actualizar',
    connectEnabledHelp: 'Eres visible para usuarios de Bloom cercanos que tengan Connect activado.',
    connectDisabledHelp: 'Activa Connect para que usuarios de Bloom cercanos puedan descubrirte.',
    connectEnableLabel: 'Activar Connect',
    connectPrivacyNote: 'Tu ubicación exacta nunca se comparte, solo que estuviste cerca.',
    connectPeopleHeading: 'Personas con las que te has conectado',
    connectEmptyTitle: 'Aún no hay conexiones',
    connectEmptyHelp: 'Cuando te cruces con otros usuarios de Connect, aparecerán aquí.',

    // Early access screen
    earlyAccessSupporterTitle: 'Eres colaborador',
    earlyAccessHasAccess: 'Tienes acceso anticipado a las próximas funciones.',
    earlyAccessRequiredTitle: 'Se requiere ser colaborador',
    earlyAccessRequiredBody: 'Conviértete en colaborador para desbloquear el acceso anticipado a las próximas funciones.',
    earlyAccessViewSupporter: 'Ver opciones de colaborador',

    // Map screen
    mapLoadFailed: 'No se pudo cargar el mapa. Inténtalo de nuevo.',
    mapLoadingEvents: 'Cargando eventos…',
    mapEmptyHelp: 'No hay eventos para mostrar en el mapa por ahora.',
    mapDismiss: 'Cerrar',
    mapInCommunity: 'En {name}',
    mapViewEvent: 'Ver evento',

    // Supporter screen
    supporterLoadFailed: 'No se pudo cargar el estado de colaborador. Inténtalo de nuevo.',
    supporterConnectFailed: 'No se pudo conectar con el pago de colaborador. Inténtalo de nuevo.',
    supporterLoadingStatus: 'Cargando estado de colaborador…',
    supporterSignInPrompt: 'Inicia sesión para ver tu estado de colaborador.',
    supporterActiveTitle: 'Eres colaborador',
    supporterLinkedTitle: 'Cuenta vinculada',
    supporterNotConnectedTitle: 'No conectado',
    supporterActiveBody: 'Gracias por apoyar a Bloom. Tienes acceso a los beneficios de colaborador.',
    supporterLinkedBody: 'Tu cuenta de Patreon está vinculada, pero el estado de colaborador aún no está activo.',
    supporterNotConnectedBody: 'Conecta tu cuenta de Patreon para convertirte en colaborador y desbloquear beneficios.',
    supporterVerifiedOn: 'Verificado el {date}',
    supporterReconnect: 'Reconectar',
    supporterConnect: 'Conectar Patreon',

    // Post detail screen
    postYou: 'Tú',
    postNotFoundTitle: 'Publicación no encontrada',
    postNotFoundHelp: 'Es posible que esta publicación haya sido eliminada o no exista.',
    postNoRepliesYet: 'Aún no hay respuestas. Sé el primero en responder.',
    postRepliesHeading: 'Respuestas',
    postWriteReplyPlaceholder: 'Escribe una respuesta…',
    postSendReply: 'Enviar respuesta',

    // Edit post screen
    postEditMissingFields: 'Completa un título y una descripción antes de guardar.',
    postEditUpdatedTitle: 'Publicación actualizada',
    postEditOk: 'Aceptar',
    postEditUpdateFailed: 'No se pudo actualizar tu publicación. Inténtalo de nuevo.',
    postEditForbiddenTitle: 'No puedes editar esta publicación',
    postEditForbiddenHelp: 'No tienes permiso para editar esta publicación.',
    postEditSaveChanges: 'Guardar cambios',

    // Public profile screen
    profileUnblockConfirmTitle: 'Desbloquear usuario',
    profileBlockConfirmTitle: 'Bloquear usuario',
    profileUnblockConfirmMessage: 'Podrá ver tus publicaciones e interactuar contigo de nuevo.',
    profileBlockConfirmMessage: 'No verán las publicaciones del otro ni podrán interactuar.',
    profileUnblock: 'Desbloquear',
    profileBlock: 'Bloquear',
    profileMoreOptions: 'Más opciones',
    profileTitle: 'Perfil',
    profileNotFoundTitle: 'Perfil no encontrado',
    profileBlockedHelp: 'Has bloqueado a este usuario.',
    profileNoPostsHelp: 'Este usuario aún no ha publicado nada.',
    profileUserBlockedTitle: 'Usuario bloqueado',
    profileNoPostsTitle: 'Aún no hay publicaciones',

    // Edit profile screen
    profileEditPhotoAccessMessage: 'Permite el acceso a fotos para actualizar tu foto de perfil.',
    profileEditUnsupportedFileTitle: 'Archivo no compatible',
    profileEditUnsupportedFileSupporterMessage: 'Elige una imagen JPEG, PNG, WEBP o GIF.',
    profileEditUnsupportedFileMessage: 'Elige una imagen JPEG, PNG o WEBP. Los GIF son un beneficio de colaborador.',
    profileEditFileTooLargeTitle: 'Archivo demasiado grande',
    profileEditFileTooLargeMessage: 'Elige una imagen de menos de {size}MB.',
    profileEditDisplayNameLength: 'El nombre a mostrar debe tener entre 1 y 50 caracteres.',
    profileEditBioLength: 'La biografía debe tener {limit} caracteres o menos.',
    profileEditUpdatedTitle: 'Perfil actualizado',
    profileEditUpdatedMessage: 'Tus cambios se han guardado.',
    profileEditUpdateFailed: 'No se pudo actualizar tu perfil.',
    profileEditChangePhoto: 'Cambiar foto',
    profileEditDisplayName: 'Nombre a mostrar',
    profileEditUsername: 'Nombre de usuario',
    profileEditBio: 'Biografía',
    profileEditBioPlaceholder: 'Cuéntale a tus comunidades sobre ti',

    // Post card / options menu
    postAlreadyReportedTitle: 'Ya reportado',
    postReportedTitle: 'Reportado',
    postAlreadyReportedMessage: 'Ya has reportado esta publicación.',
    postReportedMessage: 'Gracias por avisarnos. Nuestro equipo revisará esta publicación.',
    postDeleteTitle: 'Eliminar publicación',
    postDeleteConfirm: '¿Seguro que quieres eliminar esta publicación? Esta acción no se puede deshacer.',
    postCouldNotDeleteTitle: 'No se pudo eliminar',
    postManageTitle: 'Administrar publicación',
    postOptionsTitle: 'Opciones de publicación',
    postReportPost: 'Reportar publicación',
    postLocationLabel: 'Ubicación:',
    postPostedOn: 'Publicado el {date}',
    postUnlike: 'Ya no me gusta',
    postLike: 'Me gusta',
    postLikeCount: '{count} me gusta',
    postReplyCount: '{count} respuestas',
  },
} as const;

type TranslationParams = Record<string, string | number>;

export type TranslationKey = keyof typeof strings.en;

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => Promise<void>;
  t: (key: TranslationKey, params?: TranslationParams) => string;
};

function interpolate(template: string, params?: TranslationParams) {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (match, token) => {
    const value = params[token];
    return value === undefined ? match : String(value);
  });
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'en',
  setLanguage: async () => {},
  t: (key, params) => interpolate(strings.en[key], params),
});

export function LanguageProvider({ children }: PropsWithChildren) {
  const { session } = useAuth();
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    let active = true;
    if (!session?.user.id) return;

    supabase
      .from('profiles')
      .select('Language')
      .eq('id', session.user.id)
      .single()
      .then(({ data, error }) => {
        if (!active) return;
        if (!error && (data?.Language === 'en' || data?.Language === 'es')) {
          setLanguageState(data.Language);
        }
      });

    return () => { active = false; };
  }, [session?.user.id]);

  const setLanguage = useCallback(async (nextLanguage: LanguageCode) => {
    if (!session?.user.id) return;
    const { error } = await supabase.from('profiles').update({ Language: nextLanguage }).eq('id', session.user.id);
    if (error) throw error;
    setLanguageState(nextLanguage);
  }, [session?.user.id]);

  const t = useCallback(
    (key: keyof typeof strings.en, params?: TranslationParams) => interpolate(strings[language][key], params),
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
