import { access, cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const legacyRoot = resolve(projectRoot, "legacy")

// Each sync gets its own version stamp. Browsers cache these static legacy
// scripts by exact URL, so relative imports between them (e.g. main.js
// importing supabase.js) never bust on redeploy unless the URL changes —
// this is why the site used to keep serving stale legacy JS until someone
// hard-refreshed. Appending this version to every relative import forces a
// fresh fetch after each build while still resolving to the same URL for
// every importer within one build, so shared singletons (the supabase
// client, i18n state) stay single instances within a session.
const buildVersion = Date.now().toString(36)

async function replaceDirectory(source, destination) {
    await rm(destination, { recursive: true, force: true })
    await mkdir(dirname(destination), { recursive: true })
    await cp(source, destination, { recursive: true, force: true })
}

async function replaceDirectoryIfPresent(source, destination, fallback) {
    let selectedSource = source
    try {
        await access(selectedSource)
    } catch {
        if (!fallback) return
        selectedSource = fallback
        await access(selectedSource)
    }
    await replaceDirectory(selectedSource, destination)
}

const RELATIVE_IMPORT_PATTERN = /\b(from|import)\b(\s*\(?\s*)(["'])(\.\.?\/[^"']+\.js)\3/g

async function versionRelativeImports(dir) {
    let entries
    try {
        entries = await readdir(dir, { withFileTypes: true })
    } catch {
        return
    }

    await Promise.all(entries.map(async (entry) => {
        const fullPath = join(dir, entry.name)
        if (entry.isDirectory()) {
            await versionRelativeImports(fullPath)
            return
        }
        if (!entry.name.endsWith(".js")) return

        const original = await readFile(fullPath, "utf8")
        const versioned = original.replace(
            RELATIVE_IMPORT_PATTERN,
            (_match, keyword, gap, quote, specifier) => `${keyword}${gap}${quote}${specifier}?v=${buildVersion}${quote}`,
        )
        if (versioned !== original) {
            await writeFile(fullPath, versioned, "utf8")
        }
    }))
}

await Promise.all([
    replaceDirectoryIfPresent(resolve(legacyRoot, "js"), resolve(projectRoot, "public/js")),
    replaceDirectoryIfPresent(resolve(legacyRoot, "css"), resolve(projectRoot, "public/css")),
    replaceDirectoryIfPresent(
        resolve(legacyRoot, "Assets"),
        resolve(projectRoot, "public/Assets"),
        resolve(projectRoot, "src/Assets"),
    ),
    replaceDirectoryIfPresent(resolve(legacyRoot, "mobile/js"), resolve(projectRoot, "public/mobile/js")),
    replaceDirectoryIfPresent(resolve(legacyRoot, "mobile/css"), resolve(projectRoot, "public/mobile/css")),
    replaceDirectoryIfPresent(
        resolve(legacyRoot, "mobile/Assets"),
        resolve(projectRoot, "public/mobile/Assets"),
        resolve(projectRoot, "src/Assets"),
    ),
])

await Promise.all([
    versionRelativeImports(resolve(projectRoot, "public/js")),
    versionRelativeImports(resolve(projectRoot, "public/mobile/js")),
])

await mkdir(resolve(projectRoot, "src/generated"), { recursive: true })
await writeFile(
    resolve(projectRoot, "src/generated/legacyBuildVersion.ts"),
    `// Auto-generated by scripts/sync-legacy.mjs on every sync. Do not edit by hand.\nexport const LEGACY_BUILD_VERSION = ${JSON.stringify(buildVersion)}\n`,
    "utf8",
)
